global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'my-service'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['proxy:8080']